### ISSUE TITLE
Multi Source Inventory (MSI)

### ISSUE THREAD

**Issue by misha-kotov** [magento/backlog#5]
The Multisource Inventory (MSI) extension to Magento enables you to specify the locations, or sources, of your products. You use these sources to fulfill customers’ orders that you sell through your websites. All progress for the MSI project is tracked at https://github.com/magento-engcom/msi. The #msi channel on the Community Engineering Slack is also used for community discussions of the project.

**Comment by mbrinton01** [comment]
Released in 2.3.0.
