### ISSUE TITLE
Cloud Developer Tools

### ISSUE THREAD

**Issue by misha-kotov** [magento/backlog#9]
### ECE-Tools

**Summary:** ECE-Tools is the latest and most stable version of scripts & tools designed to manage & deploy Cloud projects. Starting version 2002.0.9 ECE-Tools support Magento 2.1.x. Latest version of this package is badly required to have all available features enabled for your environment. ECE-Tools supports all Magento Core versions starting 2.1.4 and higher.

**Contribution:** https://github.com/magento/ece-tools (available for participants of Partner Rewards Program)

### In-dev Improvements:
**Release 2002.0.14**
- [x] Re-worked `deploy` phase, resolving most known failure conditions;
- [x] Stabilized cron functionality for 2.1.x core versions (fixes applied handle scheduling better)
- [x] Enforced TLS 1.2+ support for cloud projects
- [x] Extended environment configuration checks on every deployment (ideal state checks)
- [x] Multiple other fixes & improvements

**Release 2002.0.15**
- [x] Support for environment-specific configuration files (.magento.env.yaml)
- [x] Re-worked ADMIN_* variables usage (possible deprecation and/or removal)
- [x] Docker for local development - added cron support
- [x] Docker for local development - added ElasticSearch (image & optional automatic configuration)
- [x] Docker for local development - added possibility to use DB dump locally
- [x] Docker for local development - added RabbitMQ (image & optional automatic configuration)

**Comment by YPyltiai** [comment]
This was completed.
